import torch
import multiprocessing as mp
from core.deep_cfr_new import DeepCFRAgent
import ray
import random
from agents.test_agents import RandomAgent
import numpy as np
@ray.remote
def parallel_traversal_chunk(env_maker, main_weights, chunk_size, iteration):
    # 1. Rebuild isolated environment and agents
    env = env_maker()
    
    # Force to CPU to avoid CUDA initialization errors in child processes
    local_main_agent = DeepCFRAgent(device='cpu', memory_size=75000) 
    local_main_agent.advantage_net.load_state_dict(main_weights)
        
    # 2. Run the chunk of traversals
    for _ in range(chunk_size):
        env.reset(options={'small_blind_player': random.randint(0, 1)})
        local_main_agent.cfr_traverse(env, iteration, depth=0)
        
    # 3. Return the memory generated by this specific worker
    # (Assuming your memory classes have an internal list or dict you can return)
    mem = local_main_agent.advantage_memory
    n = len(mem) # Uses our custom __len__ to get valid count
    
    adv_batch = None
    if n > 0:
        adv_batch = {
            # .copy() forces NumPy to pack just these 'n' rows tightly for Ray
            "s": mem.states[:n].copy(),
            "a": mem.actions[:n].copy(),
            "r": mem.regrets[:n].copy(),
            "i": mem.iters[:n].copy(),
            
            # Vectorized priority math
            "p": np.power(mem.priorities[:n], 1 / mem.alpha, dtype=np.float32)
        }

    # -------------------------------------------------------------
    # 2. Extract Strategy Memory (Direct Array Slicing)
    # -------------------------------------------------------------
    strat_mem = local_main_agent.strategy_memory
    n_strat = len(strat_mem)
    
    strat_batch = None
    if n_strat > 0:
        strat_batch = {
            "s": strat_mem.states[:n_strat].copy(),
            "p": strat_mem.probs[:n_strat].copy(),
            "i": strat_mem.iters[:n_strat].copy(),
            "rp": strat_mem.reach_probs[:n_strat].copy()
        }

    # -------------------------------------------------------------
    # 3. Instantly clear the worker's memory for the next loop
    # -------------------------------------------------------------
    # Because we use pre-allocated arrays, we don't delete the arrays.
    # We just reset the tracker to 0, which overwrites old data instantly!
    mem.total_seen = 0
    strat_mem.total_seen = 0
    return adv_batch, strat_batch

